# Generated by Django 5.2.17 on 2026-09-21 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storm_studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='storm_studio.job'),
        ),
    ]
