# Generated by Django 5.2.17 on 2026-09-21 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storm_studio', '0002_job_previous'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='operation',
            field=models.CharField(default='train', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_jobs', to='storm_studio.job'),
        ),
    ]
