from django.urls import path
from storm_studio import views

urlpatterns = [
    path('', views.home, name='home'),
    path('studies/<int:study_id>/archive/', views.archive_study, name='archive-study'),
    path('preparations/<int:revision_id>/archive/',
         views.archive_preparation, name='archive-preparation'),
    path('scaffold/', views.scaffold, name='scaffold'),
    path('visualize/<uuid:job_id>/<str:visualizer>/', views.visualization, name='visualization'),
    path('studies/<int:study_id>/import/', views.import_data, name='import-data'),
    path('studies/<int:study_id>/data/upload/', views.upload_data, name='upload-data'),
    path('studies/<int:study_id>/data/associations/', views.save_asset_sessions,
         name='save-asset-sessions'),
    path('studies/<int:study_id>/assets/<int:asset_id>/video/prepare/',
         views.prepare_video_preview, name='prepare-video-preview'),
    path('studies/<int:study_id>/assets/<int:asset_id>/video/', views.video_preview,
         name='video-preview'),
    path('studies/<int:study_id>/data/inventory/', views.inventory_data, name='inventory-data'),
    path('studies/<int:study_id>/data/pose-preview/<int:dataset_revision_id>/',
         views.pose_preview_data, name='pose-preview'),
    path('studies/<int:study_id>/data/label-corrections/',
         views.correct_dataset_label, name='label-correction'),
    path('studies/<int:study_id>/data/video-timeline-review/',
         views.review_video_timeline, name='review-video-timeline'),
    path('studies/<int:study_id>/data/video-discontinuities/',
         views.save_video_discontinuities, name='save-video-discontinuities'),
    path('studies/<int:study_id>/data/partitions/', views.save_session_partitions, name='save-session-partitions'),
    path('studies/<int:study_id>/pipeline-preview/', views.preview_pipeline, name='pipeline-preview'),
    path('studies/<int:study_id>/assistant/', views.assistant, name='assistant'),
    path('studies/<int:study_id>/snapshot/', views.snapshot, name='snapshot'),
    path('studies/<int:study_id>/<str:section>/', views.page, name='page'),
    path('status/<int:study_id>/', views.status, name='status'),
    path('plans/<int:revision_id>/run/', views.run, name='run'),
    path('revisions/<int:revision_id>/revise/', views.revise, name='revise'),
    path('jobs/<uuid:job_id>/<str:operation>/', views.action, name='action'),
    path('reports/<uuid:job_id>/<str:format>/', views.report, name='report'),
    path('reports/studies/<int:study_id>/aggregate/<str:format>/', views.aggregate_report, name='aggregate-report'),
    path('reports/studies/<int:study_id>/freeze/', views.freeze_study_report,
         name='freeze-study-report'),
    path('reports/frozen/<int:revision_id>/bundle/', views.frozen_study_bundle,
         name='frozen-study-bundle'),
    path('reports/frozen/<int:revision_id>/<str:format>/', views.frozen_study_report,
         name='frozen-study-report'),
]
